server.port: 8081

spring:
  cloud:
    stream:
      bindings:
        output:
          destination: local-queue
          group: producer-consumer
          binder: rabbit
      binders:
        rabbit:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                host: localhost
                port: 5672
                username: guest
                password: guest
